// Realistic mock data for Phase 1 static UI

export const mockWorkspace = {
  id: 'ws_01',
  name: 'Acme Growth',
  slug: 'acme-growth',
  plan: 'pro',
}

export const mockUser = {
  id: 'usr_01',
  name: 'Maksym Stepanenko',
  email: 'm@acme.io',
  avatarUrl: null,
  role: 'OWNER',
}

export const mockAccounts = [
  {
    id: 'acc_01',
    platform: 'REDDIT',
    displayName: 'u/growth_ops_1',
    username: 'growth_ops_1',
    authStatus: 'CONNECTED',
    warmupStatus: 'READY',
    healthStatus: 'HEALTHY',
    reputationScore: 78,
    riskScore: 12,
    dailyActionLimit: 40,
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'acc_02',
    platform: 'TELEGRAM',
    displayName: 'SignalBot Alpha',
    username: 'signalbot_alpha',
    authStatus: 'CONNECTED',
    warmupStatus: 'WARMING',
    healthStatus: 'HEALTHY',
    reputationScore: 42,
    riskScore: 8,
    dailyActionLimit: 20,
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'acc_03',
    platform: 'X',
    displayName: '@growthacme',
    username: 'growthacme',
    authStatus: 'CONNECTED',
    warmupStatus: 'READY',
    healthStatus: 'AT_RISK',
    reputationScore: 61,
    riskScore: 45,
    dailyActionLimit: 15,
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 90),
  },
  {
    id: 'acc_04',
    platform: 'FACEBOOK',
    displayName: 'Acme Ventures FB',
    username: 'acme_ventures',
    authStatus: 'DISCONNECTED',
    warmupStatus: 'IDLE',
    healthStatus: 'UNKNOWN',
    reputationScore: 0,
    riskScore: 0,
    dailyActionLimit: 20,
    lastSeenAt: null,
  },
]

export const mockSources = [
  {
    id: 'src_01',
    platform: 'REDDIT',
    sourceType: 'subreddit',
    name: 'r/SaaS',
    url: 'https://reddit.com/r/saas',
    joinStatus: 'joined',
    priority: 9,
    tags: ['saas', 'b2b', 'tools'],
    ingestionStatus: 'active',
    signalCount: 34,
  },
  {
    id: 'src_02',
    platform: 'REDDIT',
    sourceType: 'subreddit',
    name: 'r/entrepreneur',
    url: 'https://reddit.com/r/entrepreneur',
    joinStatus: 'joined',
    priority: 7,
    tags: ['startup', 'growth'],
    ingestionStatus: 'active',
    signalCount: 21,
  },
  {
    id: 'src_03',
    platform: 'TELEGRAM',
    sourceType: 'group',
    name: 'SaaS Founders Chat',
    url: null,
    joinStatus: 'joined',
    priority: 8,
    tags: ['saas', 'founders'],
    ingestionStatus: 'active',
    signalCount: 17,
  },
  {
    id: 'src_04',
    platform: 'X',
    sourceType: 'keyword_stream',
    name: '#outreach #saas',
    url: null,
    joinStatus: 'active',
    priority: 6,
    tags: ['outreach', 'saas'],
    ingestionStatus: 'paused',
    signalCount: 8,
  },
  {
    id: 'src_05',
    platform: 'REDDIT',
    sourceType: 'subreddit',
    name: 'r/startups',
    url: 'https://reddit.com/r/startups',
    joinStatus: 'joined',
    priority: 7,
    tags: ['startup', 'early-stage'],
    ingestionStatus: 'active',
    signalCount: 29,
  },
]

export const mockSignals = [
  {
    id: 'sig_01',
    platform: 'REDDIT',
    source: 'r/SaaS',
    authorName: 'jeffk_founder',
    title: 'Anyone know a good tool for Reddit outreach at scale?',
    bodyText:
      'We are trying to reach SaaS buyers on Reddit and X but keep getting banned. Any tools that actually work and stay under the radar?',
    intentScore: 94,
    urgencyScore: 88,
    fitScore: 92,
    aiSummary: 'Founder explicitly searching for outreach automation with platform safety requirements.',
    extractedNeed: 'Reddit + X outreach tool with account safety',
    recommendedAction: 'Engage with value reply + soft pitch',
    status: 'NEW',
    postedAt: new Date(Date.now() - 1000 * 60 * 22),
  },
  {
    id: 'sig_02',
    platform: 'REDDIT',
    source: 'r/entrepreneur',
    authorName: 'startup_maria_b',
    title: 'How are you guys finding leads without cold email?',
    bodyText:
      'Cold email is basically dead in our niche. Looking for alternatives that dont feel spammy. Been thinking Reddit/communities but not sure how to do it systematically.',
    intentScore: 87,
    urgencyScore: 72,
    fitScore: 89,
    aiSummary: 'Founder actively looking for cold email alternatives, open to community outreach.',
    extractedNeed: 'Alternative to cold email for lead generation',
    recommendedAction: 'Reply with community outreach methodology',
    status: 'NEW',
    postedAt: new Date(Date.now() - 1000 * 60 * 47),
  },
  {
    id: 'sig_03',
    platform: 'TELEGRAM',
    source: 'SaaS Founders Chat',
    authorName: 'dmitry_saas',
    title: null,
    bodyText:
      'What CRM does everyone use for tracking leads from multiple channels? Trying to consolidate Telegram + Reddit + email into one pipeline.',
    intentScore: 76,
    urgencyScore: 61,
    fitScore: 83,
    aiSummary: 'Founder looking for multi-channel CRM with pipeline management.',
    extractedNeed: 'Multi-channel lead pipeline management tool',
    recommendedAction: 'DM with product positioning',
    status: 'REVIEWED',
    postedAt: new Date(Date.now() - 1000 * 60 * 95),
  },
  {
    id: 'sig_04',
    platform: 'REDDIT',
    source: 'r/startups',
    authorName: 'rachel_pmf',
    title: 'We tried every outreach tool and they all suck',
    bodyText:
      'Lemlist, Instantly, Hunter — tried them all. They work for email but nothing works well for Reddit/Telegram where our buyers actually hang out.',
    intentScore: 91,
    urgencyScore: 85,
    fitScore: 95,
    aiSummary: 'High frustration signal — explicitly rejected existing tools, prime for unique value proposition.',
    extractedNeed: 'Reddit + Telegram native outreach solution',
    recommendedAction: 'High priority — engage immediately',
    status: 'ENGAGED',
    postedAt: new Date(Date.now() - 1000 * 60 * 180),
  },
  {
    id: 'sig_05',
    platform: 'X',
    source: '#outreach #saas',
    authorName: '@growth_hacker_tom',
    title: null,
    bodyText:
      'Spent 3 hours manually going through Telegram groups for leads today. There HAS to be a better way.',
    intentScore: 82,
    urgencyScore: 79,
    fitScore: 88,
    aiSummary: 'Pain signal around manual lead discovery in Telegram groups.',
    extractedNeed: 'Automated Telegram lead discovery',
    recommendedAction: 'Reply with product angle',
    status: 'NEW',
    postedAt: new Date(Date.now() - 1000 * 60 * 320),
  },
]

export const mockLeads = [
  {
    id: 'lead_01',
    platform: 'REDDIT',
    displayName: 'jeffk_founder',
    handle: 'u/jeffk_founder',
    pipelineStage: 'CONTACTED',
    temperature: 'hot',
    estimatedValue: 490,
    tags: ['reddit', 'high-intent'],
    lastInteractionAt: new Date(Date.now() - 1000 * 60 * 60),
    signalScore: 94,
  },
  {
    id: 'lead_02',
    platform: 'REDDIT',
    displayName: 'rachel_pmf',
    handle: 'u/rachel_pmf',
    pipelineStage: 'REPLIED',
    temperature: 'hot',
    estimatedValue: 890,
    tags: ['reddit', 'frustrated-with-competitors'],
    lastInteractionAt: new Date(Date.now() - 1000 * 60 * 30),
    signalScore: 91,
  },
  {
    id: 'lead_03',
    platform: 'TELEGRAM',
    displayName: 'dmitry_saas',
    handle: '@dmitry_saas',
    pipelineStage: 'QUALIFIED',
    temperature: 'warm',
    estimatedValue: 2400,
    tags: ['telegram', 'team-account', 'pipeline-need'],
    lastInteractionAt: new Date(Date.now() - 1000 * 60 * 120),
    signalScore: 76,
  },
  {
    id: 'lead_04',
    platform: 'X',
    displayName: 'growth_hacker_tom',
    handle: '@growth_hacker_tom',
    pipelineStage: 'NEW',
    temperature: 'warm',
    estimatedValue: 290,
    tags: ['x', 'automation-pain'],
    lastInteractionAt: new Date(Date.now() - 1000 * 60 * 320),
    signalScore: 82,
  },
  {
    id: 'lead_05',
    platform: 'REDDIT',
    displayName: 'startup_maria_b',
    handle: 'u/startup_maria_b',
    pipelineStage: 'NEGOTIATION',
    temperature: 'hot',
    estimatedValue: 990,
    tags: ['reddit', 'decision-maker'],
    lastInteractionAt: new Date(Date.now() - 1000 * 60 * 15),
    signalScore: 87,
  },
]

export const mockDashboardKPIs = {
  leadsDetectedToday: 18,
  highIntentSignals: 7,
  repliesSent: 12,
  dmConversions: 3,
  activeAccounts: 3,
  atRiskAccounts: 1,
}

export const mockActivityFeed = [
  {
    id: 'act_01',
    type: 'signal',
    message: 'New high-intent signal detected from r/SaaS',
    actor: 'system',
    time: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'act_02',
    type: 'reply',
    message: 'Reply approved and sent to u/rachel_pmf',
    actor: 'Maksym S.',
    time: new Date(Date.now() - 1000 * 60 * 12),
  },
  {
    id: 'act_03',
    type: 'dm',
    message: 'DM conversation started with dmitry_saas',
    actor: 'growth_ops_1',
    time: new Date(Date.now() - 1000 * 60 * 34),
  },
  {
    id: 'act_04',
    type: 'warmup',
    message: 'Warmup action completed: upvote in r/entrepreneur',
    actor: 'growth_ops_1',
    time: new Date(Date.now() - 1000 * 60 * 58),
  },
  {
    id: 'act_05',
    type: 'lead',
    message: 'Lead startup_maria_b moved to Negotiation',
    actor: 'Maksym S.',
    time: new Date(Date.now() - 1000 * 60 * 75),
  },
  {
    id: 'act_06',
    type: 'signal',
    message: 'Signal dismissed: low fit score (23) from r/memes',
    actor: 'system',
    time: new Date(Date.now() - 1000 * 60 * 110),
  },
]

export const mockDmConversations = [
  {
    id: 'dm_01',
    lead: { displayName: 'dmitry_saas', handle: '@dmitry_saas', platform: 'TELEGRAM' },
    pipelineStage: 'QUALIFIED',
    lastMessage:
      'That makes sense. Do you have a demo I can see? Our team uses Telegram heavily for lead gen.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 12),
    unreadCount: 1,
    summary: 'Interested in demo, team use case with Telegram + Reddit.',
  },
  {
    id: 'dm_02',
    lead: { displayName: 'startup_maria_b', handle: 'u/startup_maria_b', platform: 'REDDIT' },
    pipelineStage: 'NEGOTIATION',
    lastMessage: 'What does the Pro plan include exactly? Trying to justify to my co-founder.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 45),
    unreadCount: 2,
    summary: 'Pricing discussion, co-founder approval needed.',
  },
  {
    id: 'dm_03',
    lead: { displayName: 'jeffk_founder', handle: 'u/jeffk_founder', platform: 'REDDIT' },
    pipelineStage: 'CONTACTED',
    lastMessage: 'Ok interesting. How does the warmup work exactly?',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 90),
    unreadCount: 0,
    summary: 'Asking about warmup mechanism after initial reply.',
  },
]
